{
    "directory name": "llvm-project/lldb/test/API/tools/lldb-dap/exception",
    "score.sum": 0,
    "sha.latest": "01263c6c6fb495a94fe0ccbb1420bb1ec8460748",
    "time.latest": 1717969142.538451,
    "formatted_time": "2024-06-10 03:09:02.538454",
    "filescores": {
        "main.cpp": 0,
        "Makefile": 0,
        "TestDAP_exception.py": 0
    },
    "subdirscores": {}
}